version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4467:4467"
    environment:
      PRISMA_CONFIG: |
        port: 4467
        managementApiSecret: mysecret42
        databases:
          default:
            connector: postgres
            host: prisma-db
            port: 5432
            user: root
            password: prisma
            migrations: true
  db:
    container_name: prisma-db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres:/var/lib/postgres
volumes:
  postgres: